dist: xenial
language: python
python:
- 3.5
- 3.6
- 3.7
env:
- NAPALM=2.4.0
matrix:
  include:
  - python: 3.6
    env: TOXENV=black
install:
- pip install tox-travis
- pip install coveralls
deploy:
  provider: pypi
  skip_existing: true
  user: bewing
  on:
    tags: true
    branch: master
  password:
    secure: mk0a0sOT4Qja0BPRNTvsRU7+vhyEBktZ6rcmdcd0tYM2jqUZzo/zPqPrXDX0Chjl/h4J7jg2LIgBF2Zmmh4SO86un1z77V4DVAYh4U+EGJSFKBNcEZbb0ihRQ0F2mfpiD2TXu7UM47YiPWAvVgWoi/NsIJh/gQWV4qmo/IN0rSrhAsNFyJtwa2uZHIvr3kBnUFSBLu4iScI8Ajf8Nxsz/xbw0HjHHLDd9qE8uE2jc+OVXkTScGRkDyC8sthFSRot6pODDD5Xf2xPFDip6txvS/9i9j8bCsSfIKJg9Syicy/jhXJqI7bKZW6aceqdCuzczDErhuVXvOuYmKlQ0Ks9+6AsU5RICXxOGX3hzw6imFiare1BR0+1i9Aap45fZJ4k3VXfrAaYIm4MZU4n4qNTMOyAbd85BDO1injMgWwg0TKvDzbN7pbRp159rhEN/x/Lee5JN7+ZXsWR5Nx7dmX47zTRTuCitGbkI671goqoaa03uRJGwIpFNsgIFzZI+KiKH/w5CcDE+v10HX+HNMTPkDbq3f2eL5GgAtjVJ3EezXkgmSS8aECU9yUBTThgkwxb0+vHDVHAnH4z02aMK+SiJQ+F3Wv2yaujm7bXEnOTOSkrXNGE0VPZLucn/z5+eUaNsMcXQ9mwGBq6mWOOsDc2Mf4GmhAcEhxu1KUqS/v7W0c=
script:
- tox
after_success:
- coveralls
